### ISSUE TITLE
Emoji's Break Text input 

### ISSUE THREAD

**Issue by Alttaf** [unidoc/unipdf-examples#71] opened 2019-11-29 17:32 UTC
While using an emoji the unidoc newParagraph function, the text is not displayed correctly see screen shots

when entering this this character sequence 

`p = creator.NewParagraph(text)`

Ç % { < a@E£@!&%@&^!@($**))_))*!@)(£&*^%^! 
without the emoji it prints all the characters
![image](https://user-images.githubusercontent.com/5350178/69883938-29149880-12ce-11ea-8deb-a4055fad7826.png)

Ç % { < a@E£@!&%@&^!@($**))_))*!@)(£&*^%^! /😀
with emoji at the end verticalises the text and does not print emoji

![image](https://user-images.githubusercontent.com/5350178/69883846-e18e0c80-12cd-11ea-8cd2-39e9d1d86fac.png)

**Comment by gunnsth** [comment] 2019-12-01 22:26
@Alttaf We cannot reproduce this. Can you attach a full contained example (with PDF and code that is runnable)?
Also, can you confirm that this is the behavior on the newest unipdf version?  (3.3.0).

Thanks.

**Comment by Alttaf** [comment] 2019-12-02 10:33
running versions 2.2.0 
github.com/unidoc/unidoc v2.2.0+incompatible

you will need to add a grid.pdf to the same location as the main.go file 
[grid.pdf](https://github.com/unidoc/unipdf-examples/files/3910766/grid.pdf)

main.go below

`package main

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/unidoc/unidoc/pdf/creator"
	pdf "github.com/unidoc/unidoc/pdf/model"
)

const (
	inputPath = "grid.pdf"
)

func emojiTest(page *pdf.PdfPage,
	c *creator.Creator) error {
	var rotation float64

	var p *creator.Paragraph

	mBox, err := page.GetMediaBox()

	if err != nil {
		return err
	}

	pageWidth := mBox.Urx - mBox.Llx
	pageHeight := mBox.Ury - mBox.Lly

	if page.Rotate != nil {
		rotation = float64(*page.Rotate)
	}

	type Page struct {
		X, Y       float64
		Rotation   float64
		Text       string
		FontSize   float64
		EnableWrap bool
	}

	// COMMENT OUT THE APPROPRIATE TEXT TO RUN BOTH EXAMPLES
	// WITH AND WITHOUT EMOJIS

	//emoji text
	emojiText := "text with emoji 😀 🧟"

	// no emoji text
	//emojiText := "text no emoji"

	textEdit := Page{
		X:          0.4 * pageWidth,
		Y:          0.4 * pageHeight,
		Rotation:   rotation,
		Text:       emojiText,
		FontSize:   12,
		EnableWrap: true,
	}

	p = creator.NewParagraph(textEdit.Text)
	p.SetFontSize(textEdit.FontSize)
	p.SetEnableWrap(textEdit.EnableWrap)
	p.SetAngle(textEdit.Rotation)
	p.SetPos(textEdit.X, textEdit.Y)

	err = c.Draw(p)

	if err != nil {
		return err
	}
	return nil
}

func main() {

	inputFile, err := os.Open(inputPath)
	if err != nil {
		fmt.Errorf("failed to open input PDF :: %v", err)
	}

	defer func() {
		if err := inputFile.Close(); err != nil {
			fmt.Errorf("failed to close input PDF file :: %v", err)
		}
	}()

	outputFile, err := ioutil.TempFile("./", "ys-signer-pdf-editor-*-.pdf")
	if err != nil {
		fmt.Errorf("failed to create output temp file :: %v", err)
	}

	c := creator.New()
	c.SetPageMargins(
		0.00,
		0.00,
		0.00,
		0.00,
	)

	p, err := pdf.NewPdfReader(inputFile)
	if err != nil {
		fmt.Printf("error loading file :: %v ", err)
	}
	page, err := p.GetPage(1)

	if err != nil {
		fmt.Printf("get page error :: %v ", err)
	}

	c.AddPage(page)

	err = emojiTest(page, c)

	if err != nil {
		fmt.Printf("emojiTest error :: %v ", err)
	}

	err = c.WriteToFile(outputFile.Name())

	if err != nil {
		fmt.Printf("writing file error :: %v ", err)
	}

}
`

**Comment by Alttaf** [comment] 2019-12-02 12:50
The behaviour on the latest version of unidoc with the creator.New() syntax does not make the text vertical, it does not print the emoji's hower, is there something is should be doing differently?

**Comment by gunnsth** [comment] 2019-12-04 19:57
To print emoji's you need to have a font that supports those as well as encoding.  I am not aware of this having been done before with unipdf so needs some investigation and possibly a new feature.

Created a ticket in unipdf repository for tracking. Will close this one
https://github.com/unidoc/unipdf/issues/206

**Closed by gunnsth** 2019-12-04 19:57 UTC
